"""PostgreSQL persistence and explicit schema initialization (psycopg 3)."""
import os
import re
from pathlib import Path

import psycopg
from psycopg import Connection, sql
from psycopg.rows import dict_row
from psycopg.conninfo import conninfo_to_dict
from dotenv import load_dotenv

load_dotenv(Path(__file__).resolve().parents[2] / ".env", override=False)

SCHEMA = """
CREATE TABLE IF NOT EXISTS devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name TEXT NOT NULL,               -- 所属企业
    model TEXT NOT NULL,                      -- 型号
    serial_no TEXT NOT NULL UNIQUE,           -- 序列号（设备唯一身份）
    installed_date TEXT NOT NULL,             -- 安装日期
    last_maintenance_date TEXT NOT NULL,      -- 上次保养日期
    maintenance_interval_days INTEGER NOT NULL -- 该型号保养周期（天）
);

CREATE TABLE IF NOT EXISTS fault_kb (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model TEXT NOT NULL,                      -- 按型号组织
    symptom TEXT NOT NULL,                    -- 故障现象
    possible_cause TEXT NOT NULL,             -- 可能原因
    check_steps TEXT NOT NULL,                -- 排查步骤
    parts_involved TEXT NOT NULL DEFAULT ''   -- 涉及零件（顿号分隔）
);

CREATE TABLE IF NOT EXISTS parts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_no TEXT NOT NULL UNIQUE,             -- 零件编号
    name TEXT NOT NULL,                       -- 零件名称
    fit_models TEXT NOT NULL,                 -- 适配型号（顿号分隔）
    stock INTEGER NOT NULL DEFAULT 0,         -- 库存数量
    price DOUBLE PRECISION NOT NULL DEFAULT 0             -- 价格
);

CREATE TABLE IF NOT EXISTS tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_no TEXT NOT NULL UNIQUE,           -- 工单号 ACS-YYYYMMDD-NNN
    company_name TEXT NOT NULL,
    device_serial TEXT NOT NULL,
    model TEXT NOT NULL,
    symptom TEXT NOT NULL,
    urgency TEXT NOT NULL DEFAULT 'normal',   -- low / normal / high
    status TEXT NOT NULL DEFAULT 'pending_dispatch',
    kb_id BIGINT,                             -- 命中的知识库条目 id；NULL=知识库未收录
    advice TEXT NOT NULL DEFAULT '',          -- 给企业的初步排查建议
    created_at TEXT NOT NULL                  -- ISO 8601
);
CREATE TABLE IF NOT EXISTS company_bindings (
    scope_key TEXT PRIMARY KEY,               -- 调用者身份键（Miniclaw chatJid）
    company_name TEXT NOT NULL DEFAULT '',    -- 绑定企业（role=company 时有效）
    role TEXT NOT NULL DEFAULT 'company',     -- company（企业客户）/ internal（售后内部）
    bound_at TEXT NOT NULL                    -- ISO 8601
);

CREATE TABLE IF NOT EXISTS maintenance_plans (
    model TEXT PRIMARY KEY,                   -- 型号 → 保养项目映射（任务书第五节：清单来自映射，不许模型即兴生成）
    items TEXT NOT NULL,                      -- 保养项目（顿号分隔）
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS part_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_no TEXT NOT NULL UNIQUE,          -- 申领单号 PR-YYYYMMDD-NNN
    ticket_no TEXT NOT NULL,                  -- 关联工单（任务书第六节：无工单不受理）
    part_no TEXT NOT NULL,
    part_name TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    requested_by TEXT NOT NULL,               -- 申领人身份（scope_key）
    status TEXT NOT NULL DEFAULT 'pending_approval',  -- pending_approval / approved / rejected
    finance_comment TEXT NOT NULL DEFAULT '', -- 财务审批意见（人工闸门，智能体不代决）
    created_at TEXT NOT NULL,
    decided_at TEXT
);

ALTER TABLE tickets ADD COLUMN IF NOT EXISTS ticket_type TEXT NOT NULL DEFAULT 'repair';
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS idempotency_key TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS ticket_idempotency ON tickets(idempotency_key);
CREATE TABLE IF NOT EXISTS service_sessions (
    session_key TEXT PRIMARY KEY,
    state_json TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS service_turns (
    session_key TEXT NOT NULL,
    event_id TEXT NOT NULL,
    result_json TEXT NOT NULL,
    PRIMARY KEY (session_key, event_id)
);
"""


def database_url(db_url: str | None = None) -> str:
    url = db_url or os.environ.get("ACS_DATABASE_URL")
    if not url:
        raise ValueError("Set ACS_DATABASE_URL to a PostgreSQL connection URL")
    try:
        parameters = conninfo_to_dict(url)
    except psycopg.ProgrammingError:
        raise ValueError("A PostgreSQL connection URL is required; file databases are unsupported") from None
    if not parameters.get("dbname"):
        raise ValueError("A PostgreSQL connection URL is required; file databases are unsupported")
    return url


def connect(db_url: str | None = None) -> Connection:
    """Connect without running DDL. Use initialize/acs.seed before business traffic."""
    url = database_url(db_url)
    schema = os.environ.get("ACS_DB_SCHEMA") if db_url is None else None
    if schema and not re.fullmatch(r"[a-z_][a-z0-9_]{0,62}", schema):
        raise ValueError("ACS_DB_SCHEMA must be a valid lowercase schema name")
    conn = psycopg.connect(url, row_factory=dict_row, connect_timeout=10)
    if schema:
        try:
            conn.execute(sql.SQL("SET search_path TO {}").format(sql.Identifier(schema)))
            conn.commit()
        except Exception:
            conn.close()
            raise
    return conn


def begin_write(conn: Connection) -> None:
    """Serialize domain write transactions within the selected schema.

    Released on commit/rollback/close, including crashes. This preserves ticket
    numbering and stock checks with a coarse lock; it is not a throughput claim.
    Call again after an explicit commit before resuming a workflow write.
    """
    conn.execute("SELECT pg_advisory_xact_lock(hashtextextended(current_schema() || ':acs-write', 0))")


def initialize(db_url: str | None = None) -> None:
    with connect(db_url) as conn:
        begin_write(conn)
        conn.execute(SCHEMA, prepare=False)


if __name__ == "__main__":
    initialize()
    print("PostgreSQL schema initialized")
